export const chapters = [
  {
    comicId: 1,
    number: 1,
    title: "The Beginning",
    description: "The journey starts here.",
    status: "Complete",
    date: "2025-01-01",
    action: "Read",
    pages: ["/images/comics/comic_1.svg", "/images/comics/comic_2.svg"],
    locked: false, // Free chapter
  },
  {
    comicId: 1,
    number: 2,
    title: "The Challenge",
    description: "A new challenge arises.",
    status: "Published",
    date: "2025-02-01",
    action: "Continue Reading",
    pages: ["/images/comics/comic_4.svg", "/images/comics/comic_3.svg"],
    locked: false, // Free chapter
  },
  {
    comicId: 1,
    number: 3,
    title: "Into the Abyss",
    description: "The dark journey begins.",
    status: "Published",
    date: "2025-01-15",
    action: "Unlock 0.01 SOL",
    pages: ["/images/comics/comic_5.svg", "/images/comics/comic_6.svg"],
    locked: true, // Locked chapter
  },
  {
    comicId: 1,
    number: 4,
    title: "The Deepening Abyss",
    description: "The journey grows darker.",
    status: "Published",
    date: "2025-01-20",
    action: "Unlock 0.01 SOL",
    pages: ["/images/comics/comic_5.svg", "/images/comics/comic_6.svg"],
    locked: true, // Locked chapter
  },
  {
    comicId: 2,
    number: 1,
    title: "A New Dawn",
    description: "A new story begins.",
    status: "Published",
    date: "2025-01-15",
    action: "Read",
    pages: ["/images/chapters/chapter_1.png"],
    locked: false,
  },
  {
    comicId: 2,
    number: 2,
    title: "Rising Shadows",
    description: "Shadows emerge.",
    status: "Published",
    date: "2025-01-15",
    action: "Unlock 0.01 SOL",
    pages: ["/images/chapters/chapter_2.jpg"],
    locked: true,
  },
];